[package]
name = "rust"
version = "0.1.0"
edition = "2021"
path = "merge_sort.rs"
target="merge_sort.app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
